In [1]:
a={1,2,3,1}
print(a)

{1, 2, 3}


In [7]:
s=set([3,4,1,2,])
print(s)

{1, 2, 3, 4}


In [5]:
A={1,2,3,4,5}
B={4,5,6,7,8}                      #union
print(A|B)

{1, 2, 3, 4, 5, 6, 7, 8}


In [11]:
a={1,2,3,4,5}
b={4,5,6,7,8}
a.union(b)
b.union(a)


{1, 2, 3, 4, 5, 6, 7, 8}

In [13]:
A={1,2,3,4,5}
B={4,5,6,7,8}                 #intersection
print(A&B)

{4, 5}


In [17]:
A={1,2,3,4,5}
B={4,5,6,7,8}
print(A-B)
print(B-A)

{1, 2, 3}
{8, 6, 7}


In [19]:
A={1,2,3,4,5}
B={4,5,6,7,8}                 #symmetric
print(A^B)

{1, 2, 3, 6, 7, 8}


In [21]:
csm_students={"swathi","cherry","vishal","saipriya"}
it_students={"vishal","chandu","koushik","bharath"}
print(csm_students|it_students)     #all students who enrolled atleast one of program
print(csm_students&it_students)     #who enrolled in both programs
print(csm_students-it_students)     #who enrolled only in csm not in it
print(csm_students^it_students)     #unique to one program

{'swathi', 'vishal', 'koushik', 'cherry', 'chandu', 'saipriya', 'bharath'}
{'vishal'}
{'saipriya', 'swathi', 'cherry'}
{'swathi', 'koushik', 'chandu', 'cherry', 'saipriya', 'bharath'}


In [29]:
csm_students={"swathi","cherry","vishal","saipriya"}
csm_students.add("varshini")
print(csm_students)

{'swathi', 'vishal', 'varshini', 'cherry', 'saipriya'}


In [31]:
a={1,23,4,5}
a.add(99)
print(a)

{1, 99, 4, 5, 23}


In [35]:
a={2,3,5}
a.add(10)
a

{2, 3, 5, 10}

In [37]:
csm_students={"swathi","cherry","vishal","saipriya"}
csm_students.add("varshini")
csm_students

{'cherry', 'saipriya', 'swathi', 'varshini', 'vishal'}

In [43]:
dict={'name':'swathi','rollno':68,'college':'ace'}
print(dict['name'])

swathi


In [47]:
dict={'name':'swathi','rollno':68,'college':'ace'}
print(dict['name'])
print(dict['rollno'])
print(dict['college'])

swathi
68
ace


In [51]:
dict={'name':'swathi','rollno':68,'college':'ace'}
dict['name']='chandhana'
print(dict['name'])

chandhana


In [55]:
dict['rollno']=122
print(dict['rollno'])

122


In [57]:
dict.items()

dict_items([('name', 'chandhana'), ('rollno', 122), ('college', 'ace')])

In [101]:
students_marks={'swathi':100,'chandu':98,'koushik':78,'bharath':71}
print(students_marks)
students_marks['cherry']=99
print(students_marks)
students_marks['koushik']=88
print(students_marks)
del students_marks['bharath']
print(students_marks)
topper=max(students_marks, key=students_marks.get)
marks=students_marks[topper]
print("Topper:", topper)
print("Marks:", marks)
avg=sum(students_marks.values())/len(students_marks)
print(avg)
round(avg)

{'swathi': 100, 'chandu': 98, 'koushik': 78, 'bharath': 71}
{'swathi': 100, 'chandu': 98, 'koushik': 78, 'bharath': 71, 'cherry': 99}
{'swathi': 100, 'chandu': 98, 'koushik': 88, 'bharath': 71, 'cherry': 99}
{'swathi': 100, 'chandu': 98, 'koushik': 88, 'cherry': 99}
Topper: swathi
Marks: 100
96.25


96

In [107]:
def add():
    a=10;                   #with no arug and no returns
    b=20;
    c=a+b;
    print("The addition value is ",c)
add()

The addition value is  30


In [109]:
def add(a,b):
    c=a+b;                         #with arug 
    print("The addition value is ",c)
add(10,40)

The addition value is  50


In [ ]:
function will accepts the data, it returns the data

In [119]:
def fact(n):
    fact=1;
    i=1;
    for i in range(1,n+1):
        fact=fact*i
    print("fact is",fact)
fact(5)

fact is 120


In [121]:
def area():
    l=int(input("Enter the value: "))
    b=int(input("Enter the value: "))
    rec=l*b;
    print("Area of the rectangle",rec)
rectangle=area()



Enter the value:  2
Enter the value:  3


Area of the rectangle 6


In [123]:
def add(a,b):
    c=a+b;                   #with arug and return type
    return c;
result=add(10,20);
print(result);

30


In [125]:
def add():
    a=10;                   #with no arug and returns
    b=20;
    c=a+b;
    return c;
add()

30

In [139]:
def fact():
    n=int(input("Enter the number"))
    fact=1;
    i=1;
    for i in range(1,n+1):
        fact=fact*i
    return fact
fact1=fact();
print("The factorial is",fact1)

Enter the number 4


The factorial is 24


In [ ]:
class emp:
    def empData(self):
        self.eno=111
        self.ename="aaa"
        self.esal=10000
        print("emp number ;",self.eno)
        print("emp name ;",self.ename)
        print("emp salary ;",self.esal)
e=emp()
e.empData()

In [1]:
import numpy as np

In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr_id=np.array([1,2,3,4,5])
print(arr_id)

[1 2 3 4 5]


In [7]:
import numpy as np
arr_2d=np.array([[1,2,3,4],[7,8,9,10]])
print(arr_2d)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [9]:
import numpy as np
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
import numpy as np
random=np.random.random((2,2))
print(random)

[[0.44730059 0.42587439]
 [0.71726435 0.75869752]]


In [19]:
import numpy as np
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
import numpy as np
range_arr=np.arange(0,10,2)    #start stop end
print(range_arr)

[0 2 4 6 8]


In [25]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("DataType:",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
DataType: int32
Number of dimensions: 2


In [43]:
list1=[1,2,3]
list2=[2,3,4]
list=list1+list2
result=[a+b for a,b in zip(list1,list2)]
print(result)

[3, 5, 7]


In [45]:
a=np.array([1,5,10])
b=np.array([9,5,0])
print(a+b)      #element wise adding
print(a*b)     #element wise multiplication
print(a*2)    #scalar operation

[10 10 10]
[ 9 25  0]
[ 2 10 20]


In [47]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])              #to add 2 matrix
result=np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]


In [49]:
a=np.array([8,9,2])
b=2                                         #broadcasting
print(a+b)

[10 11  4]


In [53]:
arr=np.array([1,2,3])
print(np.exp(arr))                  #exponentiation
print(np.sqrt(arr))                 #square root
print(np.log(arr))                  #logarithm

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [57]:
arr=np.array([1,2,3,4])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Max: 4
Min: 1


In [63]:
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [67]:
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(3,2)
print(reshape)

[[1 2]
 [3 4]
 [5 6]]


In [69]:
a=np.array([1,2])
b=np.array([4,5])                                 #stacking
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 2]
 [4 5]]
[1 2 4 5]


In [71]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [73]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10                   #views shares memory
print(arr)       

copy=arr.copy()
copy[0]=10                   #shares memory
print(arr)

[10  2  3]
[10  2  3]


In [ ]:
arr=np.array([1,2,3,])
np.save('array.npy',arr)

In [97]:
arr=np.array([10,20,30,40,50])
arr=np.random.random((3,3)) #between 0 and 1
print(arr)

[[0.8371481  0.54563605 0.91968097]
 [0.72199937 0.65589241 0.74450662]
 [0.16527414 0.23278719 0.10629835]]


In [99]:
arr=np.array([10,20,30,40,50])
print(arr+5)

[15 25 35 45 55]


In [101]:
arr_2d=np.array([[10,20,30,40],[70,80,90,100]])
print(arr_2d)

[[ 10  20  30  40]
 [ 70  80  90 100]]


In [127]:
import numpy as np
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)
first_row=matrix[0]
print("The first row",first_row)
last_coloum=matrix[-1]
print("The last coloum is",last_coloum)
subarray=matrix[0:3]
print("The subarray is",subarray)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The first row [1 2 3 4 5]
The last coloum is [21 22 23 24 25]
The subarray is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
